#!/bin/bash

source /projects/pilot_spim/Christopher/pipeline_3.0/master_3.0

mkdir -p $jobs_compress

echo $jobs_compress
echo $czi_compress

for i in $parallel_timepoints

do
	for a in $angle_prep
	do
		job="$jobs_compress/compress-$i-$a.job"
		echo $job
		echo "$XVFB_RUN -a $Fiji_resave \
			-Ddir=$image_file_directory \
			-Dtimepoint=$i \
			-Dangle=$a \
			-Dpad=$pad \
			-- --no-splash $czi_compress" >> "$job"
		chmod a+x "$job"
	done
done
