#!/bin/bash
source /projects/pilot_spim/Christopher/pipeline_3.0/master_3.0
 
mkdir -p $jobs_compress

	job="$jobs_compress/compress.job"
	echo $job
	echo "#!/bin/bash" > "$job"
	echo "$XVFB_RUN -a $Fiji \
		-Dangles_compress="1" \
		-Dindex_czi="" \
		-- --no-splash $czi_compress" >> "$job"


#for index_czi in $index_czi
# 
#do
#	for angles_compress in $angles_compress
#	do
#	
#	job="$jobs_compress/compress-$index_czi-$angles_compress.job"
#	echo $job
#	echo "#!/bin/bash" > "$job"
#	echo "$XVFB_RUN -a $Fiji \
#		-Dindex_czi=$index_czi \
#		-- --no-splash $czi_compress" >> "$job"
#
#	done
#
#done
