#!/bin/bash
source /projects/pilot_spim/Christopher/pipeline_3.0/master_3.0
 
mkdir -p $jobs_fusion
 
for parallel_timepoints in $parallel_timepoints
#for i in 4 26 35 45 47 52
 
do
    job="$jobs_fusion/fusion-$parallel_timepoints.job"
    echo $job
    echo "#!/bin/bash" > "$job"
    echo "$XVFB_RUN -a $Fiji \
    	-Dimage_file_directory=$image_file_directory \
    	-Dparallel_timepoints=$parallel_timepoints \
    	-Dmerged_xml=$merged_xml \
    	-Dprocess_timepoint=$process_timepoint \
    	-Dprocess_channel=$process_channel \
    	-Dprocess_illumination=$process_illumination \
    	-Dprocess_angle=$process_angle \
    		-- --no-splash $fusion" >> "$job"
    chmod a+x "$job"
done

