#!/bin/bash
source /projects/pilot_spim/Christopher/pipeline_3.0/master_3.0
 
mkdir -p $jobs_registration
 
for parallel_timepoints in $parallel_timepoints
 
do
    job="$jobs_registration/register-$parallel_timepoints.job"
    echo $job
    echo "#!/bin/bash" > "$job"
    echo "$XVFB_RUN -a $Fiji \
    	-Dparallel_timepoints=$parallel_timepoints \
    	-Dimage_file_directory=$image_file_directory \
	-Dxml_filename=$xml_filename \
	-Dprocess_timepoint=$reg_process_timepoint \
	-Dprocess_channel=$reg_process_channel \
	-Dprocess_illumination=$reg_process_illumination \
	-Dprocess_angle=$reg_process_angle \
	-Dprocessing_channel=$reg_processing_channel \
	-Dlabel_interest_points=$label_interest_points \
	-Dtype_of_registration=$type_of_registration \
        -Dtype_of_detection=$type_of_detection \
        -Dsubpixel_localization=$subpixel_localization \
	-Dimglib_container=$imglib_container \
	-Dradius_1=$radius_1 \
	-Dradius_2=$radius_2 \
        -Dthreshold=$threshold \
	-Dinitial_sigma=$initial_sigma \
        -Dthreshold_gaussian=$threshold_gaussian \
	-Dregistration_algorithm=$registration_algorithm \
	-Dinterest_points_channel_0=$reg_interest_points_channel_0 \
	-Dinterest_points_channel_1=$reg_interest_points_channel_1 \
	-Dfix_tiles=$fix_tiles \
	-Dmap_back_tiles=$map_back_tiles \
	-Dtransformation_model=$transformation_model \
	-Dmodel_to_regularize_with=$model_to_regularize_with \
	-Dlambda=$lambda \
	-Dallowed_error_for_ransac=$allowed_error_for_ransac \
	-Ddetection_min_max=$detection_min_max \
        	-- --no-splash $registration" >> "$job"
    chmod a+x "$job"
done

