#!/bin/bash
source /projects/tomancak_lightsheet/Valia/Valia/new_pipeline/master
 
job="$jobs_xml/merge.job"
echo $job
echo "#!/bin/bash" > "$job"
echo "$XVFB_RUN -a $Fiji \
	-Dxml_path=$dir \
	-Dxml_filename=$xml_filename \
		-- --no-splash $merge_xml" >> "$job"
chmod a+x "$job"
